import test from 'node:test';
import assert from 'node:assert/strict';
import { parseExportOptions, getDocTitle, getDocAuthor, getDocDate, getHtmlHead } from '../src/export-options.js';

function mkDoc(keywords) {
  return { keywords };
}

// ---- defaults ----------------------------------------------------------------

test('THE FIX: parseExportOptions returns real org\u2019s own actual defaults when no #+OPTIONS: line is present at all', () => {
  const options = parseExportOptions(mkDoc([]));
  assert.deepEqual(options, { toc: true, num: true, sup: 't', author: true, date: true, creator: false });
});

test('parseExportOptions handles a document with keywords but no OPTIONS keyword the same way', () => {
  const options = parseExportOptions(mkDoc([{ key: 'TITLE', value: 'Hello' }]));
  assert.deepEqual(options, { toc: true, num: true, sup: 't', author: true, date: true, creator: false });
});

// ---- toc: ----------------------------------------------------------------------

test('THE EXACT REQUEST: toc:2 sets a depth limit, matching real Emacs org-mode\u2019s own confirmed behavior', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'toc:2' }])).toc, 2);
});

test('toc:nil disables the table of contents entirely', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'toc:nil' }])).toc, false);
});

test('toc:t (or any other non-numeric, non-nil value) means "on, full depth"', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'toc:t' }])).toc, true);
});

// ---- num: ------------------------------------------------------------------

test('num:nil disables section numbering', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'num:nil' }])).num, false);
});

test('THE FIX: toc: and num: are genuinely independent -- toc:1 with num: left at its own default (t) keeps num true, matching real Emacs org-mode\u2019s own confirmed behavior (a depth-limited ToC listing, but still full section numbers throughout the body)', () => {
  const options = parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'toc:1' }]));
  assert.equal(options.toc, 1);
  assert.equal(options.num, true);
});

// ---- ^: (sub/superscript) -------------------------------------------------------

test('^:nil requires nothing (subscript/superscript disabled entirely)', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: '^:nil' }])).sup, 'nil');
});

test('^:{} requires explicit braces', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: '^:{}' }])).sup, '{}');
});

test('^:t (or the default, unset) means real org\u2019s own liberal default -- no braces required', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: '^:t' }])).sup, 't');
  assert.equal(parseExportOptions(mkDoc([])).sup, 't');
});

// ---- author: / date: / creator: -------------------------------------------------

test('author:nil / date:nil suppress those fields from appearing in the export even when present', () => {
  const options = parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'author:nil date:nil' }]));
  assert.equal(options.author, false);
  assert.equal(options.date, false);
});

test('THE EXACT REQUEST: creator defaults to false (nil), matching the request\u2019s own documented default exactly', () => {
  assert.equal(parseExportOptions(mkDoc([])).creator, false);
});

test('creator:t enables the "Generated by ..." notice', () => {
  assert.equal(parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'creator:t' }])).creator, true);
});

// ---- multiple keys / lines, "last wins" -----------------------------------------

test('multiple keys chained on one #+OPTIONS: line all apply together', () => {
  const options = parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'toc:nil num:nil author:nil date:nil creator:t' }]));
  assert.deepEqual(options, { toc: false, num: false, sup: 't', author: false, date: false, creator: true });
});

test('THE FIX: multiple #+OPTIONS: lines merge, with a later line\u2019s own value for the same key winning -- matching this app\u2019s own established "last wins" convention for repeated file keywords elsewhere (see startup-config.js)', () => {
  const options = parseExportOptions(
    mkDoc([
      { key: 'OPTIONS', value: 'num:nil' },
      { key: 'OPTIONS', value: 'toc:3' },
      { key: 'OPTIONS', value: 'num:t' }, // overrides the earlier num:nil
    ])
  );
  assert.equal(options.num, true);
  assert.equal(options.toc, 3);
});

test('an unrecognized #+OPTIONS: key is silently ignored rather than erroring', () => {
  const options = parseExportOptions(mkDoc([{ key: 'OPTIONS', value: 'tags:nil todo:nil num:nil' }]));
  assert.equal(options.num, false);
  // No crash, no unexpected extra properties.
  assert.deepEqual(Object.keys(options).sort(), ['author', 'creator', 'date', 'num', 'sup', 'toc']);
});

// ---- getDocTitle / getDocAuthor / getDocDate -------------------------------------

test('getDocTitle/getDocAuthor/getDocDate extract and trim their own respective keyword values', () => {
  const doc = mkDoc([
    { key: 'TITLE', value: '  My Test Document  ' },
    { key: 'AUTHOR', value: 'Jane Doe' },
    { key: 'DATE', value: '2026-01-15' },
  ]);
  assert.equal(getDocTitle(doc), 'My Test Document');
  assert.equal(getDocAuthor(doc), 'Jane Doe');
  assert.equal(getDocDate(doc), '2026-01-15');
});

test('getDocTitle/getDocAuthor/getDocDate all return null when the document has none of these keywords', () => {
  const doc = mkDoc([]);
  assert.equal(getDocTitle(doc), null);
  assert.equal(getDocAuthor(doc), null);
  assert.equal(getDocDate(doc), null);
});

// ---- THE FIX: case-insensitive keyword matching --------------------------------

test('THE FIX: getDocTitle/getDocAuthor/getDocDate match a lowercase #+title:/#+author:/#+date: too, matching real Emacs org-mode\u2019s own confirmed case-insensitive keyword parsing (a user\u2019s own reported case: #+title:/#+date: silently produced no title/date at all before this fix)', () => {
  const doc = mkDoc([
    { key: 'title', value: 'org-pwa README.org' },
    { key: 'author', value: 'Jane Doe' },
    { key: 'date', value: '2026-08-20' },
  ]);
  assert.equal(getDocTitle(doc), 'org-pwa README.org');
  assert.equal(getDocAuthor(doc), 'Jane Doe');
  assert.equal(getDocDate(doc), '2026-08-20');
});

test('mixed-case #+Title:/#+Author:/#+Date: also match', () => {
  const doc = mkDoc([
    { key: 'Title', value: 'T' },
    { key: 'Author', value: 'A' },
    { key: 'Date', value: 'D' },
  ]);
  assert.equal(getDocTitle(doc), 'T');
  assert.equal(getDocAuthor(doc), 'A');
  assert.equal(getDocDate(doc), 'D');
});

// ---- getHtmlHead ---------------------------------------------------------------

test('THE EXACT REQUEST: multiple #+HTML_HEAD: lines concatenate, joined by newlines in source order, matching real Emacs org-mode\u2019s own confirmed behavior', () => {
  const doc = mkDoc([
    { key: 'HTML_HEAD', value: '<style>' },
    { key: 'HTML_HEAD', value: 'body { color: red; }' },
    { key: 'HTML_HEAD', value: '</style>' },
  ]);
  assert.equal(getHtmlHead(doc), '<style>\nbody { color: red; }\n</style>');
});

test('a single #+HTML_HEAD: line works too', () => {
  const doc = mkDoc([{ key: 'HTML_HEAD', value: '<link rel="stylesheet" href="x.css">' }]);
  assert.equal(getHtmlHead(doc), '<link rel="stylesheet" href="x.css">');
});

test('getHtmlHead returns null (not an empty string) when there are none at all', () => {
  assert.equal(getHtmlHead(mkDoc([])), null);
});

test('THE FIX: a lowercase #+html_head: matches too, matching real Emacs org-mode\u2019s own confirmed case-insensitive keyword parsing', () => {
  const doc = mkDoc([{ key: 'html_head', value: '<style>x</style>' }]);
  assert.equal(getHtmlHead(doc), '<style>x</style>');
});
