For the below changes add support and the associated documentation for the feature/cpaability change.


1/ Some modifications we need to make long-pressing on a header does the equivalent of "+" action button, and add a sub header. If the variable org-header-prepend is t then the new sub-header is created at top of; otherwise the new sub-header is created at the end of the headline.


2/ Add support for org-clock-in, org-check-out and org-clock-display. Replace the "+" in action button -- if org-clock-in (▶️) is selected then the clock starts as described below and becomes a toggle the org-clock-out (⏹) is displayed to execute org-clock-out. See the descriptions below. On the View>TODO screen to add a check-box to enable org-clock-display.


*** org-clock-in
Start the clock on the current item (clock-in). This inserts the ‘CLOCK’ keyword together with a timestamp. If this is not the first clocking of this item, the multiple ‘CLOCK’ lines are wrapped into a ‘LOGBOOK’ drawer.

The clock time shown is all time ever clocked in for this task and its children.


*** org-clock-out
Stop the clock (clock-out). This inserts another timestamp at the same location where the clock was last started. It also directly computes the resulting time in inserts it after the time range as ‘=>HH:MM’.


*** org-clock-display
Display time summaries for each subtree in the current buffer. This puts overlays at the end of each headline, showing the total time recorded under that heading, including the time of any subheadings. You can use visibility cycling to study the tree, but the overlays disappear when you change the buffer.


3/ Add the below variables (local and global) and its associated functionality, where missing. Ensure all variables are in the table, and sort the table (and the description) by the variable name. There could be a section that shows the equivalent variables for the #+STARTUP directives -- the three items below (sorted)


org-startup-folded 'overview|'content|'showall|'showeverything (default = showeverything)


org-startup-with-inline-images t|nil (default = nil)


org-log-done: 'time|'note (default = nil, no logging). I believe documentation is missing for this item.

-----

1/ Move the location of return menu from the lower left to the lower right of the screen. Add support for an extra's floating button (☰) with a vertical popup menu on the lower left-hand size. This extra's button is configured as follows:


In the global variables section we will have a variable org-extra-menu. This variable is used to construct a menu. The format of the variable is as follows:
when there are just characters before the ; those are the key for a capture template. If that menu item is selected execute the indicated capture template. If the information is of the form 'function then execute the specified function. Make sure to add support for org-clock-out, there will be more functions added later, when appropriate.


org-extra-menu: "t;⭐ Tracking" 
                "j;📔 Journal" 
                "c;✅ Checklist" 
                "m;👥 Meeting" 
                "'org-clock-out;⏹ clock-out"

2/ Add support for an ASCII exporter the variable org-ascii-text-width defines the maximum line width (in characters) for wrapping text paragraphs during an ASCII, Latin-1, or UTF-8 text export. By default, this value is set to 72 characters.


3/ The order of the File>export buttons should be "ASCII", "Calendar", "HTML", and "Markdown".

-----

1/ Update capture templates replace %N with @# (make sure this functionality works) - it is the built-in Org-mode table formula constant that evaluates to the current row number, acting as an automatic ID/counter. It should support simple operations like '@# + n', where n is an integer (negative or positive or zero). %N is non-standard and @# is standard org-mode.


2/ Add :prepend support in capture templates. To prepend rather than append text when adding items in Org-mode, use the :prepend t property inside your Emacs org-capture-templates configuration. By default, Org-mode adds new captured information to the end of a file or headline. Setting this property forces new entries to the top.


3/ Simplify configuration for Settings>Agenda Files again, do not make this hard -- should not require programming to understand. There should be one entry per line like the below:

#+BEGIN_EXAMPLE
scheme:path/filename.org
github:journal.org
#+END_EXAMPLE

-----

1/ Update documentation still some extra ~ in the documentation, like in the Inline text markup header there is a line that starts with "Inside a ~QUOTE~ or ~CENTER~ block" that seems incorrect.


In the Capture Templates section there is a section that contains "b*ullet list item, *c*heck list item, *m*eeting notes ..." This is not formatted correctly -- I believe the intent was for the first letter to be highlighted. Fix please.


In the "Differences from Emacs org-mode" there are some inconsistencies after the "Agenda" section. "No babel, no command palette." is on the same lines as the text and all the other sections are not.  The same for "Undo/redo", "Search", ... make all items in a section consistent. Make consistent, I prefer things be on the same line -- not a "Name bolded" a new line with a bullet. Make all them like the "No babel, no command palette." section.


Make sure these documentation quirks are checked in the app and in the help section because they seem to be using different code.


After this round of changes has been released lets revisit what is required to have a single engine for both normal "rendering" and the help -- the read-only equivalent. I believe a solid refactoring could reduce the code and maintenance -- it might be a big job initially; however, overtime it should be better.

-----

yes, scope out refile. Here are some rough ideas.



Default Values: By default, org-refile-targets (is nil) only allows refiling within the current buffer (file) up to level 1. org-refile-targets like something like:

[figure out the exact syntax - we will use a global variable/local variable.

org-refile-targets "scheme:name.org maxlevel: . 3" "scheme:name1.org" "org-agenda-files level: . 1"

When no level or maxlevel is given for org-refile-targets, Org mode defaults to level 1 headlines (top-level headings) in the current buffer.

Default Behavior

Target File: The current buffer (nil)
Heading Level: Level 1 headlines only (:level . 1)

Key Details

Current Buffer: If unspecified, Org mode looks only at the active file you are working in rather than your agenda files.

Top-Level Only: Subheadings (level 2 and deeper) are ignored unless you explicitly configure :maxlevel or :level.

===
Add variable org-log-done with the below options.


*** org-log-done 'time
Then each time you turn an entry from a TODO (not-done) state into any of the DONE states, a line ‘CLOSED: [timestamp]’ is inserted just after the headline. If you turn the entry back into a TODO item through further state cycling, that line is removed again. If you turn the entry back to a non-TODO state, that line is also removed, unless you set org-closed-keep-when-no-todo to non-nil.
‘#+STARTUP: logdone’


*** org-log-done 'note


Update Settings and add an area where we can set variables, one per line using the syntax similar to the Local variables but this is global (all files). An example of setting variables would be:


org-log-done: 'time
org-agenda-start-on-workday: 1


For global variables they can be saved like the other sections. Also they can be exported / imported. They are applied as they are saved.


The precedence order of the configuration should follow the current emacs org-mode and allow overrides in the file using #+STARTUP or "# Local Variables:" but lets document the precedence. I also believe we should keep these three section close together possibly creating a new heading Configuration and three subheaders or all at the top-level. 



Add support for the following BLOCKS:


'#+BEGIN_VERSE' - keeps line breaks in a region.


'#+BEGIN_QUOTE' - quoting a passage that is indented on both the left and the right margin. Ensure that our implementation does indentation for both the right and left margin.


'#+BEGIN_CENTER' - centering of text.


To enforce a line break within a paragraph, use '\\' at the end of a line. Make sure this is documented in the inline text markup section.


NAVAGATION

Should we add a ⏎ character at the lower right to return to the previous place/location after select a link; otherwise, on a mobile device we can not easily navigate around in documents that have a TOC.

===
More > ? - Help inconsistencies.

In the getting started section numbering restarts for at 1 for "Edit. Every ..." and the next line is "2. Tap Save". These should have continued at 3 then used 4.


General Documentation:

Document/List the #+BEGIN_XX we support like XX={COMMENT, QUOTE, EXAMPLE, CENTER, SRC} and the options.



Update:

Change File > Export > {Markdown, HTML} to change "Whole file" to "This file".


In File>Export>Calendar add support to "Choose a heading" because it is useful to export a subset and to maintain consistency.

===
Documentation fixes:


BUG: ~ character seems to be the escape character, but it is visible and makes plenty examples hard to read like in the base of 'Block content' examples. Other examples include in the Inline text markup there are plenty of examples where the syntax shows "~*bold text*~", however the third column is the syntax and the third column should be the result bold; however, the 3rd column is not bold it just shows "*bold text*"; it should show the text bolded. The issue occurs more than just in tables. For example, there are is a  "logdone~/ ~lognotedone".


Can we add support to render the inline text markup appropriately throughout org files? Lets fix this bug plus the escaping problems.


The org file is mostly correct on github, especially the tables.; however, there are many examples of ~ being displayed on github. An example is "The :ARCHIVE: tag and ARCHIVE_TIME~/~ARCHIVE_FILE~/~ARCHIVE_OLPATH~/~ARCHIVE_CATEGORY properties".


BUG: When using more > ? (help) is not rendering correctly in certain areas; however, opening the raw file readme.org displays correctly.

The specific areas are:

 * Getting started starting at "Local file ..." down through "Import file" is not indented.
 
 * Editing your outline starting at "SCHEDULED / DEADLINE ..." down  through "Properties" is not indented.
 
 * other areas described above about the possible escape character, that works on github.
 
===
* Add support for footnotes.

* Add iCalendar export.

** Variables
*** org-log-done 'time
Then each time you turn an entry from a TODO (not-done) state into any of the DONE states, a line ‘CLOSED: [timestamp]’ is inserted just after the headline. If you turn the entry back into a TODO item through further state cycling, that line is removed again. If you turn the entry back to a non-TODO state, that line is also removed, unless you set org-closed-keep-when-no-todo to non-nil.
‘#+STARTUP: logdone’

*** org-log-done 'note
You are then prompted for a note, and that note is stored below the entry with a ‘Closing Note’ heading.
‘#+STARTUP: lognotedone’

** Logging Details
Ensure we have a :LOGBOOK: drawer for Progress logging. Also, add support on the Agenda screen to display logging details. Make sure to add the needed support for changing state in TODO's on a per-keyword basis for this. This is achieved by adding special markers ‘!’ (for a timestamp) or ‘@’ (for a note with timestamp) in parentheses after each keyword. For example, with the setting

#+TODO: TODO(t) WAIT(w@/!) | DONE(d!) KILL(k@)

You not only define global TODO keywords and fast access keys, but also request that a time is recorded when the entry is set to ‘DONE’, and that a note is recorded when switching to ‘WAIT’ or ‘KILL’. The setting for ‘WAIT’ is even more special: the ‘!’ after the slash means that in addition to the note taken when entering the state, a timestamp should be recorded when leaving the ‘WAIT’ state, if and only if the target state does not configure logging for entering it. So it has no effect when switching from ‘WAIT’ to ‘DONE’, because ‘DONE’ is configured to record only a timestamp. But when switching from ‘WAIT’ back to ‘TODO’, the ‘/!’ in the ‘WAIT’ setting now triggers a timestamp even though ‘TODO’ has no logging configured.




Capture - Refile - Archive
Refile and Copy

===
continue, but before rebuilding the updated zip,  update the documentation that describes %<FORMAT> by sorting the entries in the table ... %a, %A ...

===
Lets investigate an item. Occasionally the app changes the filename to indicate it has been modified -- changes to red color. However, there isn't anything in the history log -- I noticed this before and can not figure out what the app thinks has been modified. I don't believe I have modified anything.

Lets simplify agenda files to be a JSON array like this
["scheme1:path1", "scheme2:path2"] this will be much simpler and concrete examples would be ["github:journal.org", "github:todo.org"].

Re-arrange More> menu so it is Search, Capture, History, +, ?.

===
Lets address some issues and concerns I found whilst testing/reviewing: Testing was conducted on a Pixel 9a, running android 17.


Bugs:
1/ Bug: Templates do not provide a UI when capturing to a file. Make 
entry UI consistent between file and no file, a popup might be a good choice.


2/ Bug: main menu scrolls and is not visible when adding a capture entry -- this has been a persistent problem with the header line not being permanently displayed (please come up with a permanent fix). This might not be a problem if a popup is used for checkitem input.


Feature Changes:
3/ Make the capture ui have two buttons per row, so more templates can be displayed on the screen.


4/ Capture templates should remain visible until dismissed (an item tapped on the main menu). This will allow multiple templates to be selected without having to go through the three key sequence More>Capture>Template.


Documentation changes:
5/ Update documentation put actual unicode characters in the documentation and not the escape sequence, for example do not use \u22ee but add ⋮, the same for \u2192 use →, there are more examples, especially in the Undo/redo and History section. The Export section also has some unicode escapes that should be replaced with the actual characters.


Indicate somewhere that org-archive-confirm is something we contrived for this application and is not a true org-mode variable. It is misleading to suggest that t matching real org, given it isn't a variable used by org-mode.


Remove names like Jennifer and dates that could be real and use Jane Doe, Mary and a made up date like <2000-01-01 Sat +1y> we don't want to have any information that could be mapped back to a real individual.


Update the %<FORMAT> to have a table with a description of the format-time-string specifiers supported because it is hard to understand the values without having to look at a secondary source which might be hard to find.


===
1/ Update settings and details about inline text markup; however, make sure you deliver working code before my credits run out. We can take on the other parts later, but always deliver some incremental value that I can use now.


Add another font size (other) on the same line as the existing font size, that allows adjusting of the font size for other elements (like tables).


Allow export/import of settings, all elements (appearance, templates, webdav, github, etc.).


Update search so when we switch to text mode you keep the current location, context -- stay on the same line (or near the same line).


Ensure we have support the the below inline text markup and the documentation accurate describes the markup.


Bold: *bold text*

Italic: /italic text/

Underline: _underline text_

Strikethrough: +strikethrough text+

Verbatim / Code: =verbatim text= or ~code text~


A line consisting of only dashes, and at least 5 of them, is exported as a horizontal line.


‘^’ and ‘_’ are used to indicate super- and subscripts. To increase the readability of ASCII text, it is not necessary, but OK, to surround multi-character sub- and superscripts with curly braces.

The org-use-sub-superscripts variable controls the functionality of super and subscripts.
 
 Configuration Values:
 
 t (default): Every _ and ^ triggers a subscript or superscript.
 
 nil: Disables automatic interpretation of _ and ^ entirely.
 
 {}: Only interprets subscripts and superscripts if the characters are wrapped in curly brackets (e.g., a_{b} works, but a_b is ignored).

===
2/
* Add support for archiving


C-c C-x C-s org-archive-subtree is the command


#+ARCHIVE or the variable org-archive-location variable defines where completed or old subtrees are sent when you run the archive command (C-c C-x C-s or C-c $). The default value is "%s_archive::", which means subtrees move to a separate file ending in _archive in the same folder.


Structure of the Variable / configuration.


Formatted as a string with two parts joined by a double-colon (::).


First part (File path): The destination file name. %s turns into the current file's name without its path. If left empty before the ::, it archives inside the current file.


Second part (Headline path): A specific heading path inside that file (e.g., * Finished Tasks) where the entry goes. If left empty, entries go to the root level of the file.


Common Examples


"%s_archive::": Default. Archives to a sibling file named filename.org_archive as top-level entries.


"::* Archived Tasks": Archives inside the active file under a top-level heading called * Archived Tasks.


"~/org/archive.org::": Archives everything into a single central file located at ~/org/archive.org.


"~/org/archive.org::* %s": Archives into a central file under a heading named after the original source file.


===
3/ Deliver code and documentation for the below; however, make sure you deliver working code before my credits run out. We can take on the other parts later, but always deliver some incremental value that I can use now.


BUG: links do not render for https://nickhigham.wordpress.com/ - link without a description.


BUG? (no) links do not render for doi: — Digital Object Identifiers for scientific and academic papers.


* Add support for multiple open documents and the ability to switch between them.


* Add support in capture templates to support more than the current org file.


* Add support to load local/relative image paths, by product of the above.


For the above we should support the below link types:

- http: / https:

- file: — Local or remote files (e.g., file:~/documents/notes.org).

- github: - path to file inrepository.

- webdav: - path to file in repository.


See examples below that we should allow where possible for all the above link types:


Absolute Path: [[file:/home/user/documents/notes.org]] — Points to a specific location from the root directory.


Relative Path: [[file:projects/todo.org]] — Looks for the file starting from the directory of your current Org file.


Specific Headline: [[file:~/notes.org::*Project Alpha]] — Opens the file and jumps directly to the "Project Alpha" headline.


Text Search: [[file:~/notes.org::exact phrase]] — Opens the file and searches for the first instance of "exact phrase".


===
4/  Deliver code and documentation for the below; however, make sure you deliver working code before my credits run out. We can take on the other parts later, but always deliver some incremental value that I can use now.

* Update code to support inheritance from ancestor headings (tags, and properties), and update code and documentation.


In Search menu (and documentation) change the button label from [Regex] to Regex.


Update documentation to remove the section that starts (Archived-heading cycling behavior used to be documented ...) no need to document mistakes or changes in the current documentation. That type of detail clutters the existing documentation and doesn't add value.


* Provide support for undo/redo capability.


* Export to markdown and PDF. Export entire buffer or select a selected header.

===
🎊 Holidays

|Date|Code|Holiday (2026)|
|20260101|F,1,1|New Year's Day|
|20260119|3,1,1|MLK Jr. Day|
|20260214|F,14,2|Valentine's Day|
|20260216|3,1,2|Washington's Birthday|
|20260308|2,0,3|Begin Daylight Savings|
|20260510|2,0,5|Mother's Day|
|20260525|L,1,5|Memorial Day|
|20260619|F,19,6|Juneteenth|
|20260621|3,0,6|Father's Day|
|20260704|F,4,7|Independence Day|
|20260907|1,1,9|Labor Day|
|20261012|2,1,10|Columbus Day|
|20261101|1,0,11|End Daylight Savings|
|20261111|F,11,11|Veterans Day|
|20261126|4,4,11|Thanksgiving Day|
|20261225|F,25,12|Christmas Day|

---
|Date|Code|Holiday (2027)|
|20270101|F,1,1|New Year's Day|
|20270118|3,1,1|MLK Jr. Day|
|20270214|F,14,2|Valentine's Day|
|20270215|3,1,2|Washington's Birthday|
|20270314|2,0,3|Begin Daylight Savings|
|20270509|2,0,5|Mother's Day|
|20270531|L,1,5|Memorial Day|
|20270619|F,19,6|Juneteenth|
|20270620|3,0,6|Father's Day|
|20270704|F,4,7|Independence Day|
|20270906|1,1,9|Labor Day|
|20271011|2,1,10|Columbus Day|
|20271107|1,0,11|End Daylight Savings|
|20271111|F,11,11|Veterans Day|
|20271125|4,4,11|Thanksgiving Day|
|20271225|F,25,12|Christmas Day|

===
Lets update the action buttons and functionality.


update the timestamp/scheduled/deadline editor to be more general and also support CRUD for tags, properties, and priorities.
- timestamps (keep existing)
- scheduled (keep existing)
- deadline (keep existing)
- tags, new UI element just have the tags 
- properties, new UI, edit key value pairs -- not just raw text.
- priority editor, new UI, allow setting/viewing priority

Replace '#' with an archive button. Make sure this works in conjunction with properties in the general editor above.

Now we need to update buttons displayed as there will be fewer buttons because we no longer need the following buttons '#', tags, properties.


The buttons should be as follows:

Row 1: edit header, edit text, general editor, +, up arrow, down arrow

Row 2: todo, table, archive, x (delete), left, right


update documentation to reflect these changes. The folding section is garbled because there is a table there. Local Variables should have the default for org-contacts-birthday-property in the table. the org-contacts-anniversaries section is garbled (indentation lost) because preformatted text is not working. Remove the "Supersedes" paragraph because that is not longer needed. Remove vestigal notes from the file. We do have regex support.


Add some keybindings especially for the larger browser -- use defaults from emacs-org where feasible and that will work in the web environment.


===
When using github or webdav can we get a list of files and let the user selects from it without having to find the filenames from a secondary source?

===
Let's redo the anniversary stuff ...


Build code that implements the following.



Configuration:
# org-contacts-birthday-property: EVENT



Examples are below.
* John Doe
  :PROPERTIES:
  :EVENT: 1990-05-15 Birthday
  :END:



* Mary & Jim
  :PROPERTIES:
  :EVENT: 2015-08-22 Wedding Anniversary
  :END:


How it renders: The text trailing the date automatically substitutes into the agenda display string, generating line items like: John Doe: Birthday (36) or Mary & Jim: Wedding Anniversary (11).


* Anniversaries & Birthdays
%%(org-contacts-anniversaries)



The above would scan your org file(s) for the :EVENT: property (or whatever is specified in org-contacts-birthday-property (EVENT is the default). It calculates an age dynamically.It displays a line in your daily/weekly agenda showing the event and the age (e.g., "John Doe: Birthday (36)").  If YYYY is set to nil then the year is not known and the age cannot be determined and "(xx)" will be shown.



We will deprecate "%%(org-anniversary YEAR MONTH DAY) " once the above is functioning. I do not want to keep an extra copy of the birthday and anniversary information.


====
Make sure we adhere to emacs as the standard and follow it and point out any descrepancies. here is what show all should do, and ensure the other modes strictly follow emacs.



cycle-visibility doesn't seem to be working (again), because I have some headers tagged with ARCHIVE and they are being expanded. org-cycle-open-arched-trees should be nil, thus the header should be folded and swiping should skip subtrees.



The showall visibility state in Org mode removes all folding on text bodies and headlines in the buffer, meaning it shows tags and tables, but does not automatically expand property drawers. [1, 2, 3, 4]

Visibility Details





Tags: Fully visible. Tags reside directly on the headline line and are always shown when folding is turned off.



Tables: Fully visible. Tables are standard body text elements and are completely unpacked.



Properties: Hidden. Property drawers (:PROPERTIES: ... :END:) act as drawers, which remain collapsed as a single line even under showall unless you explicitly unfold them or use showeverything. [1, 2, 3, 4, 5]



The showeverything visibility state in Org mode removes all folding from the entire buffer. Unlike showall, it forces every hidden element to expand completely, ensuring no text blocks remain hidden behind an ellipsis. [1]

Visibility Details





Tags: Fully visible. Like in showall, tags stay on the headline line and remain completely uncovered.



Tables: Fully visible. All tables are completely unpacked and display their raw layout.



Properties & Drawers: Fully visible. This is the primary structural difference from showall. All property drawers (:PROPERTIES: ... :END:) and custom drawers are completely expanded.



Blocks & Logbooks: Fully visible. Source code blocks, quote blocks, and time-tracking logbooks (:LOGBOOK:) are forced open. [1, 2]



continue.
===
Add support for the following in org-pwa.

The org-anniversary function in Emacs Org mode is a sexp (sexpression) diary entry used to track recurring yearly events like birthdays and anniversaries with a stable ISO year-month-day argument order and automatic age calculation.

Syntax and Usage
Format: %%(org-anniversary YEAR MONTH DAY) Text description with %d

Dynamic Age: The %d placeholder in the text automatically calculates and displays the current number of elapsed years (e.g., age or years married) in your agenda view.

Stable Arguments: Unlike standard Emacs diary functions, org-anniversary strictly uses a YEAR MONTH DAY sequence regardless of your global calendar-date-style configuration. If YYYY is set to nil then the year is not known and the age cannot be determined and %d will be -1.

Integration DetailsAgenda Display: Place these entries directly inside any of your tracked .org files (or your standard Emacs diary file) so they dynamically render in your Built-in Agenda Views.
