/**
 * #+TITLE / #+AUTHOR / #+DATE / #+OPTIONS -- shared, pure parsing for
 * every export format (HTML/ASCII/Markdown/ODT/DOCX) to build its own
 * title block and apply the same #+OPTIONS: toggles consistently,
 * rather than five separate, potentially-drifting implementations of
 * the same six keys.
 *
 * toc: and num: are genuinely INDEPENDENT in real org (confirmed
 * directly against real Emacs org-mode's own HTML export, not
 * assumed): num: controls whether headings themselves get section
 * numbers (1, 1.1, 2, ...) anywhere they're shown at all; toc:
 * controls whether a Table of Contents is generated, and to what
 * depth (an integer), independent of whatever num: is set to -- a
 * depth-limited ToC still lists every heading up to that depth even
 * with num:nil (just without number prefixes), and full section
 * numbering still applies throughout the body even with toc:nil (no
 * ToC generated at all). This app's own existing ASCII exporter
 * used to conflate the two into one combined toggle; this module
 * fixes that.
 */

const DEFAULT_OPTIONS = { toc: true, num: true, sup: 't', author: true, date: true, creator: false };

/** Parses every #+OPTIONS: line in `doc.keywords` into a single,
 *  merged `{ toc, num, sup, author, date, creator }` object -- a
 *  later value for the same key overwrites an earlier one, whether
 *  from a repeated key on one line or a second #+OPTIONS: line
 *  entirely (real org's own actual "last wins" precedence, matching
 *  this app's own already-established handling of repeated file
 *  keywords elsewhere -- see startup-config.js).
 *
 *  toc: `true` (default, "t") | `false` ("nil") | a positive integer
 *  (a depth limit, e.g. `toc:2`) -- the ToC lists headings only up to
 *  that many levels deep; num: boolean, default true; sup: `'t'` |
 *  `'nil'` | `'{}'`, default `'t'` -- matches getUseSubSuperscripts's
 *  own three-state convention directly, this is real org's own
 *  ^: key (a literal caret, not a word); author/date: boolean,
 *  default true -- whether #+AUTHOR/#+DATE (when the document
 *  actually has one) appear in the export at all; creator: boolean,
 *  default false -- whether a "Generated by ..." notice appears. */
function parseExportOptions(doc) {
  const options = { ...DEFAULT_OPTIONS };
  for (const kw of doc.keywords || []) {
    if (kw.key.toUpperCase() !== 'OPTIONS') continue;
    const tokens = kw.value.trim().split(/\s+/).filter(Boolean);
    for (const token of tokens) {
      const m = /^(\^|[a-zA-Z]+):(.+)$/.exec(token);
      if (!m) continue;
      const [, key, value] = m;
      if (key === 'toc') {
        if (value === 'nil') options.toc = false;
        else if (/^\d+$/.test(value)) options.toc = Number(value);
        else options.toc = true;
      } else if (key === 'num') {
        options.num = value !== 'nil';
      } else if (key === '^') {
        options.sup = value === 'nil' || value === '{}' ? value : 't';
      } else if (key === 'author') {
        options.author = value !== 'nil';
      } else if (key === 'date') {
        options.date = value !== 'nil';
      } else if (key === 'creator') {
        options.creator = value === 't';
      }
      // Every other real #+OPTIONS: key (tags:, todo:, pri:, e:, and
      // many more) is silently ignored -- out of scope for this
      // app's own narrower subset.
    }
  }
  return options;
}

/** `doc.keywords`' own first #+TITLE: value (real org's own "last
 *  wins" convention doesn't actually apply to #+TITLE specifically --
 *  multiple #+TITLE: lines concatenate together, but that's a rare
 *  enough case this app doesn't reproduce; the first one found is
 *  used), trimmed, or null if the document has none at all. */
function getDocTitle(doc) {
  const kw = (doc.keywords || []).find((k) => k.key.toUpperCase() === 'TITLE');
  return kw ? kw.value.trim() : null;
}

function getDocAuthor(doc) {
  const kw = (doc.keywords || []).find((k) => k.key.toUpperCase() === 'AUTHOR');
  return kw ? kw.value.trim() : null;
}

function getDocDate(doc) {
  const kw = (doc.keywords || []).find((k) => k.key.toUpperCase() === 'DATE');
  return kw ? kw.value.trim() : null;
}

export { parseExportOptions, getDocTitle, getDocAuthor, getDocDate };
